name: Run SAST scans (gitleaks | bandit)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sast-tests:
    name: Run SAST scans (gitleaks)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Execute gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Bandit Package
        if: always()
        run: pip3 install bandit
      - name: Run Bandit
        run: bandit -r .